/* Copyright 2005-2020 Kendall F. Morris

This file is part of the USF Brainstem Data Visualization suite.

    The Brainstem Data Visualiation suite is free software: you can
    redistribute it and/or modify it under the terms of the GNU General Public
    License as published by the Free Software Foundation, either version 3 of
    the License, or (at your option) any later version.

    The suite is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the suite.  If not, see <https://www.gnu.org/licenses/>.
*/


const char *structNames[] =
{
 "CENTRAL CANAL",// value = "2"
 "INF CENTRAL N",// value = "3"
 "POSTPYRAMIDAL NUCLEUS, RAPHE",// value = "5"
 "L ABDUCENS NERVE",// value = "6"
 "R ABDUCENS NERVE",// value = "7"
 "R ABDUCENS NUC",// value = "9"
 "L INF CEREBELLAR PEDUNCLE",// value = "10"
 "R INF CEREBELLAR PEDUNCLE",// value = "11"
 "L MID CEREBELLAR PEDUNCLE",// value = "12"
 "R MID CEREBELLAR PEDUNCLE",// value = "13"
 "L SUP CEREBELLAR PEDUNCLE",// value = "14"
 "R SUP CEREBELLAR PEDUNCLE",// value = "15"
 "L A-V COCHLEAR NUC",// value = "16"
 "R A-V COCHLEAR NUC",// value = "17"
 "L DOR COCHLEAR NUC",// value = "18"
 "R DOR COCHLEAR NUC",// value = "19"
 "L P-V COCHLEAR NUC",// value = "20"
 "R P-V COCHLEAR NUC",// value = "21"
 "L COCHLEAR GRAN LAYER",// value = "22"
 "R COCHLEAR GRAN LAYER",// value = "23"
 "L CUNEATE NUC",// value = "26"
 "R CUNEATE NUC",// value = "27"
 "L EX CUNEATE NUC",// value = "28"
 "R EX CUNEATE NUC",// value = "29"
 "L CUNEATE FASC",// value = "30"
 "R CUNEATE FASC",// value = "31"
 "L FACIAL NERVE",// value = "34"
 "R FACIAL NERVE",// value = "35"
 "L FACIAL NUC",// value = "36"
 "R FACIAL NUC",// value = "37"
 "L GRACILE NUC",// value = "38"
 "R GRACILE NUC",// value = "39"
 "L GRACILE FASC",// value = "40"
 "R GRACILE FASC",// value = "41"
 "L HYPOGLOSSAL NUC",// value = "42"
 "R HYPOGLOSSAL NUC",// value = "43"
 "L INFRATRIGEMINAL NUC",// value = "44"
 "L INFRATRIGEMINAL NUC",// value = "45"
 "L INF OLIVE COMPLEX",// value = "46"
 "R INF OLIVE COMPLEX",// value = "47"
 "L KOLLIKER-FUSE NUC",// value = "50"
 "R KOLLIKER-FUSE NUC",// value = "51"
 "L NUC-LAT LEMNISCUS (VEN DIV)",// value = "54"
 "R NUC-LAT LEMNISCUS (VEN DIV)",// value = "55"
 "L LAT RETICULAR NUC",// value = "56"
 "R LAT RETICULAR NUC",// value = "57"
 "L LAT RETICULAR NUC",// value = "58"
 "R LAT RETICULAR NUC",// value = "59"
 "L MARGINAL NUC, SUPERIOR CEREBELLAR PEDUNCLE",// value = "60"
 "R MARGINAL NUC, SUPERIOR CEREBELLAR PEDUNCLE",// value = "61"
 "L MED LONGITUDINAL BUNDLE",// value = "62"
 "R MED LONGITUDINAL BUNDLE",// value = "63"
 "L NUC AMBIGUUS",// value = "64"
 "R NUC AMBIGUUS",// value = "65"
 "L NUC INCERTUS",// value = "66"
 "R NUC INCERTUS",// value = "67"
 "L NUC INTERCALATUS",// value = "68"
 "R NUC INTERCALATUS",// value = "69"
 "L LOCUS COERULEUS",// value = "70"
 "R LOCUS COERULEUS",// value = "71"
 "L NUC PRAEPOSITUS HYPOGLOSSI",// value = "72"
 "R NUC PRAEPOSITUS HYPOGLOSSI",// value = "73"
 "L NUC RETROAMBIGUALIS",// value = "74"
 "R NUC RETROAMBIGUALIS",// value = "75"
 "L NUC TRACTUS SOLITARIUS",// value = "76"
 "R NUC TRACTUS SOLITARIUS",// value = "77"
 "L PONTINE GRAY (D-L DIV)",// value = "78"
 "R PONTINE GRAY (D-L DIV)",// value = "79"
 "L RETROFACIAL NUC",// value = "84"
 "R RETROFACIAL NUC",// value = "85"
 "L SUP OLIVE COMPLEX (LAT HUC)",// value = "86"
 "R SUP OLIVE COMPLEX (LAT NUC)",// value = "87"
 "L SUP OLIVE COMPLEX (MED NUC)",// value = "88"
 "R SUP OLIVE COMPLEX (MED NUC)",// value = "89"
 "L SUP OLIVE COMPLEX (PREOLIVARY)",// value = "90"
 "R SUP OLIVE COMPLEX (PREOLIVARY)",// value = "91"
 "L STATOACOUSTIC NERVE",// value = "94"
 "R STATOACOUSTIC NERVE",// value = "95"
 "L GIGANTOCELLULAR TEG FIELD",// value = "96"
 "R GIGANTOCELLULAR TEG FIELD",// value = "97"
 "L LAT TEGMENTAL FIELD",// value = "98"
 "R LAT TEGMENTAL FIELD",// value = "99"
 "L MAGNOCELLULAR TEGMENTAL FIELD",// value = "100"
 "R MAGNOCELLULAR TEGMENTAL FIELD",// value = "101"
 "L DOR TEGMENTAL NUC (PERICEN)",// value = "104"
 "R DOR TEGMENTAL NUC (PERICEN)",// value = "105"
 "L TEGMENTAL RETICULAR NUC",// value = "108"
 "R TEGMENTAL RETICULAR NUC",// value = "109"
 "L TRIGEMINAL NERVE (V)",// value = "110"
 "R TRIGEMINAL NERVE (V)",// value = "111"
 "L SENSORY NUC OF V",// value = "112"
 "R SENSORY NUC OF V",// value = "113"
 "L SPINAL TR OF V",// value = "114"
 "R SPINAL TR OF V",// value = "115"
 "L MOTOR TR OF V",// value = "116"
 "R MOTOR TR OF V",// value = "117"
 "L CAUDAL NUC, SPINAL TR OF V",// value = "118"
 "R CAUDAL NUC, SPINAL TR OF V",// value = "119"
 "L INTERPOLAR NUC, SPINAL TR OF V",// value = "120"
 "R INTERPOLAR NUC, SPINAL TR OF V",// value = "121"
 "L ORAL NUC, SPINAL TR OF V",// value = "122"
 "R ORAL NUC, SPINAL TR OF V",// value = "123"
 "L SOLITARY TRACT",// value = "126"
 "R SOLITARY TRACT",// value = "127"
 "L STRIA ACUSTICA",// value = "128"
 "R STRIA ACUSTICA",// value = "129"
 "L NUC, TRAPEZOID BODY",// value = "130"
 "R NUC, TRAPEZOID BODY",// value = "131"
 "L TRAPEZOID BODY",// value = "132"
 "R TRAPEZOID BODY",// value = "133"
 "L INF VESTIBULAR NUC",// value = "134"
 "R INF VESTIBULAR NUC",// value = "135"
 "L MED VESTIBULAR NUC",// value = "136"
 "R MED VESTIBULAR NUC",// value = "137"
 "L LAT VESTIBULAR NUC (DOR DIV)",// value = "138"
 "R LAT VESTIBULAR NUC (DOR DIV)",// value = "139"
 "R LAT VESTIBULAR NUC (VEN DIV)",// value = "141"
 "L SUP VESTIBULAR NUC (MED DIV)",// value = "142"
 "R SUP VESTIBULAR NUC (MED DIV)",// value = "143"
 "L SUP VESTIBULAR NUC (LAT DIV)",// value = "144"
 "R SUP VESTIBULAR NUC (LAT DIV)",// value = "145"
 "L DOR MOTOR NUC, VAGUS",// value = "146"
 "R DOR MOTOR NUC, VAGUS",//  value = "147"
};

int totNames=sizeof(structNames)/sizeof(char*);

 
 
